server:
  #服务端访问端口
  port: 9998
  #编码统一utf-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  multipart:
    enabled: true
    max-file-size: 10M #单个文件的最大上限max-request-size: 3M #单个请求的文件点大小上限
  tomcat:
    uri-encoding: UTF-8
    #取消post的数据限制
    max-http-form-post-size: -1

files:
  upload:
    #path: D:/upload/
    path: /src/main/resources/picutres/
#数据库连接

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      table-underline: false # 设置表明不使用下划线方式
      sql-parser-cache: true

jwtSign: sudaTqdProSign


# pageHelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


#数据库连接
spring:
  datasource:
    #    url: jdbc:mysql://111.231.53.121:3306/sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://localhost:3306/paper1010?useUnicode=true&characterEncoding=UTF-8&useSSL=false

    username: root
    password: Zhu031110
    driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
      #  格式化返回时间 yyyy-MM-dd HH:mm:ss
      date-format: yyyy-MM-dd
      time-zone: GMT+8
    mvc:
      # 前端参数格式化
      format:
        # String格式化日期
        date: yyyy-MM-dd